### ISSUE TITLE
Add option to highlight cells with matching notes

### ISSUE THREAD

**Issue by elBoberido** [black-sheep-dev/harbour-aenigma#11]
When only a few numbers are found and many notes are present, it is quite hard to spot the cells with the current selected number. It would be great to have the cells with a matching note also highlighted. This could be either part of the current `Cell` option or and additional `Cell + Notes` option.

**Comment by black-sheep-dev** [comment]
Implemented in 0.3.2

**Comment by elBoberido** [comment]
The difference between a highlighted note and non-highlighted note is barely visible, at least with the dark shadow theme.

Would it be possible to highlight the whole cell with the matching note or add a small highlighting square around the number?

**Comment by elBoberido** [comment]
It is much better now. Cells with matching notes are clearly visible and by only adding a background to the small notes it is also more visible which squares are not fully solved for a number.
