### ISSUE TITLE
Make it more visible when a cell with an existing number is overwritten

### ISSUE THREAD

**Issue by elBoberido** [black-sheep-dev/harbour-aenigma#12]
Since the cells are quite small, it is easy to touch a cell which has already a number assigned and overwrite it. To make it more visible, the old number could be moved to e.g. the top right corner for a few seconds and/or the cell could flash/blink for a few seconds.

**Comment by black-sheep-dev** [comment]
I played around with some animated cell undoing things and I don't think it is a convenient way for it.
But you are right, overwriting an already filled number by accidentally  pressing it is a nasty thing.

I decided to change the behaviour. When clicking an already filled number it will be kept as long as it differs from the current selected number. If you really want to overwrite it you need to double tap the cell. So no number should be overwritten by mistake.

This behaviour will be present in next release.

I will keep this issue open as an feature request. Maybe add this later as an option or addition.

**Comment by elBoberido** [comment]
That's also a great solution. Thanks for implementing it.

**Comment by elBoberido** [comment]
It works as expected.

How is your issue workflow? Do you expect me to close them?

**Comment by black-sheep-dev** [comment]
Will close it
