### ISSUE TITLE
Action history with bookmarks

### ISSUE THREAD

**Issue by elBoberido** [black-sheep-dev/harbour-aenigma#15]
Please add an action history like in [SudoQ](https://f-droid.org/en/packages/de.sudoq/) (second picture).

Especially when the difficulty level is high, it would be great to add a bookmark to the current state and just guess a cell. If it turns out that it was a wrong guess, one could easily go back to a known good state

**Comment by black-sheep-dev** [comment]
Bookmarks sounds like a great idea. Lets see what I can realize

**Comment by black-sheep-dev** [comment]
Implemented in actual release. Maybe later make it more fancy.
If happy please close issue otherwise keep it for discussion.

**Comment by elBoberido** [comment]
Will check it out once it hits the Jolla store

**Comment by elBoberido** [comment]
I tested the feature, but it did not help as much as I thought. I realized that I did not remember which cell I guessed after restoring the bookmark. I think what could help would be the ability to write some notes to the bookmark or have an undo and redo button. With undo and redo one could go back and forth and figure out what was done after the bookmark.

I also notice that the bookmark loading page has quite big list items for the bookmarks. Is it supposed to show a screenshot/saved state? If yes, then it is not shown on my phone.

If it is supposed to show the saved state, another option would be to mark the cells which were changed right before and after creating the bookmark.

Slightly related to this feature but maybe worth an own issue. Instead of going back to a bookmark it would be good to have the ability to go back to the latest state without a wrong number. Shall I open a feature request for this?

**Comment by black-sheep-dev** [comment]
Undo is already implemented. Redo should be possible.

Bookmarked items should show a screenshot, that's right. What OS version you using? Could you provide a console output by starting the app via console?

Going back to last good state I have already planned.

**Comment by black-sheep-dev** [comment]
> Bookmarked items should show a screenshot, that's right. What OS version you using? Could you provide a console output by starting the app via console?

Found it. Dir was not created because of a typo

**Comment by elBoberido** [comment]
Looks good now and with the option to add a description it is of much more help
